### ISSUE TITLE
Cfast freezes

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#45] opened 2022-12-19 11:59 UTC
Cfast freezes. As a result, the simulations do not run and, for example, when I set the number of simulations to 50 simulations, Aamks will stop at, say, the tenth simulation. This makes it difficult to perform a large number of simulations, because, for example, with 160 simulations done, I have 260 empty ones (they didn't run because of CFASTA suspension).

**Comment by kowalskiw** [comment] 2022-12-29 16:26
According to @akrasuski this issue is related to CFAST compilation. Compiling CFAST with Intel tool will probably resolve this issue.

Duplicate of issue #42.

**Comment by kowalskiw** [comment] 2023-01-12 16:56
On the branch `dev` the cfast is compiled with Intel tool (see #42). It should not be freezing anymore. To be observed and if bug still exists this issue will be reopened.

**Closed by kowalskiw** 2023-01-12 16:56 UTC
Labels: bug, duplicate
